#!/usr/bin/env bash
# Copyright 2026 MinIO, Inc.
# SPDX-License-Identifier: Apache-2.0

# Generate the cuFile configuration that GPU-Direct S3-over-RDMA needs on the
# CLIENT, and point CUFILE_ENV_PATH_JSON at it.
#
# WHY THIS IS MANDATORY
# ---------------------
# minio-cpp decides per request whether to use RDMA like this:
#
#     bool use_rdma = (rdma_client.cuMemObjGetDescriptor(buf, size) == 0);
#
# cuMemObjGetDescriptor pins the buffer via cuFileBufRegister. If cuFile has no
# RDMA devices configured it fails, use_rdma stays false, and the SDK quietly
# transfers over ordinary HTTP instead. Nothing errors; you just silently measure
# TCP. The tell is in cufile.log:
#
#     ERROR cufio_rdma:1430 failed to register with RDMA, no devices found in configuration
#     ERROR cufio_core:1781 cuFileBufRegister error registering buffer object for RDMA
#
# The stock /etc/cufile.json ships "rdma_dev_addr_list": [] -- empty -- so out of
# the box RDMA never engages. This script fills it with the host's actual RoCE
# NIC addresses.
#
# Usage:
#   ./12-cufile-config.sh                    # auto-detect RoCE NIC IPs
#   ./12-cufile-config.sh 10.0.0.1 10.0.0.2  # or name them explicitly
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT="$REPO_ROOT/config/cufile.json"
LOG_LEVEL="${CUFILE_LOG_LEVEL:-ERROR}"
# 64 GiB, in KiB. Generous on purpose: the failure mode when this is too low is a
# segfault inside the RDMA client, not a diagnosable error.
PINNED_MEM_KB="${PINNED_MEM_KB:-67108864}"

mkdir -p "$(dirname "$OUT")"

if [[ $# -gt 0 ]]; then
    ADDRS=("$@")
else
    # Derive the addresses from the ibverbs devices rather than from `ip addr`,
    # so we only ever list NICs that actually have an RDMA device behind them,
    # and only ports that are ACTIVE.
    mapfile -t ADDRS < <(
        for dev in /sys/class/infiniband/*; do
            [[ -e "$dev" ]] || continue
            name=$(basename "$dev")
            state=$(cat "$dev/ports/1/state" 2>/dev/null || echo "")
            [[ "$state" == *ACTIVE* ]] || continue
            for nd in "$dev"/device/net/*; do
                [[ -e "$nd" ]] || continue
                netdev=$(basename "$nd")
                ip -4 -o addr show dev "$netdev" 2>/dev/null |
                    awk '{split($4,a,"/"); print a[1]}'
            done
        done | sort -u
    )
fi

if [[ ${#ADDRS[@]} -eq 0 ]]; then
    echo "ERROR: no RoCE NIC IPv4 addresses found." >&2
    echo "       Check 'ibv_devinfo' shows PORT_ACTIVE and the netdev has an IPv4 address," >&2
    echo "       or pass the addresses explicitly: $0 <ip> [ip...]" >&2
    exit 1
fi

echo "== cuFile config for $(hostname) =="
printf '   RoCE addresses: %s\n' "${ADDRS[*]}"

addr_json=$(printf '"%s",' "${ADDRS[@]}"); addr_json="[${addr_json%,}]"

cat > "$OUT" <<EOF
{
  // Generated by scripts/setup/12-cufile-config.sh -- do not hand-edit.
  //
  // Deliberately minimal: cuFile merges nothing, so this file fully replaces
  // /etc/cufile.json for processes that set CUFILE_ENV_PATH_JSON. Only the
  // properties that affect S3-over-RDMA are set.

  "logging": {
    // Raise to TRACE when diagnosing why RDMA is not engaging; the registration
    // failures that cause silent HTTP fallback are logged here (cufile.log in
    // the process working directory).
    "level": "$LOG_LEVEL"
  },

  "execution": {
    "parallel_io": false
  },

  "properties": {
    // THE critical setting. Empty => cuFileBufRegister cannot register for RDMA
    // => minio-cpp falls back to HTTP with no error.
    "rdma_dev_addr_list": $addr_json,

    // dmabuf peer mapping is what lets the NIC DMA directly to/from GPU VRAM on
    // modern kernels. Without it, GPU buffers cannot be registered for peer-to-peer
    // transfer and device pointers fail (or crash) inside registration.
    "rdma_peer_type": "dmabuf",

    // Allow PCIe peer-to-peer DMA between the GPU and the NIC.
    "use_pci_p2pdma": true,

    // Maximum device memory this PROCESS may pin for cuFile registrations.
    // This file replaces /etc/cufile.json wholesale rather than merging, so an
    // unset value falls back to the library built-in, which is smaller than the
    // stock config's 32 GiB. A data loader holding N destination buffers of a
    // shard each pins N x shard_bytes, and exceeding the cap does not error --
    // registration fails and libminiocpp segfaults. Size this above your intended
    // in-flight footprint (fetch_workers x buffers_per_worker x shard_bytes).
    "max_device_pinned_mem_size_kb": ${PINNED_MEM_KB},

    // Fall back to a compatibility path instead of hard-failing when a
    // particular transfer cannot use the direct path.
    "allow_compat_mode": true,

    // Spread registrations across the NICs closest to each GPU. On a rail-aligned
    // host (GPU0-3 -> NIC0, GPU4-7 -> NIC1) this keeps traffic off the inter-socket
    // link.
    "rdma_load_balancing_policy": "RoundRobin",

    // Multipath + health checking: if one rail goes down, registrations move to
    // the other instead of failing the transfer.
    "rdma_multipath_enabled": true,
    "rdma_max_backup_devices": 2,
    "rdma_io_retry_count": 3,
    "rdma_io_retry_delay_ms": 100,
    "rdma_failback_enabled": true,
    "rdma_failback_delay_ms": 100,
    "rdma_health_check_interval_ms": 1000,
    "rdma_async_event_monitoring": true,
    "rdma_unhealthy_threshold": 3
  }
}
EOF

echo "   wrote $OUT"

# Make env.sh export it. Appending is idempotent: drop any previous block first.
ENVSH="$REPO_ROOT/env.sh"
if [[ -f "$ENVSH" ]]; then
    sed -i '/# --- cufile config ---/,/# --- end cufile config ---/d' "$ENVSH"
    cat >> "$ENVSH" <<EOF

# --- cufile config ---
# Without this, cuFile reads /etc/cufile.json, whose rdma_dev_addr_list is empty,
# and every RDMA transfer silently degrades to HTTP.
export CUFILE_ENV_PATH_JSON="$OUT"
# --- end cufile config ---
EOF
    echo "   env.sh exports CUFILE_ENV_PATH_JSON"
else
    echo "   NOTE: $ENVSH not found; run 10-client-env.sh first, then re-run this."
fi

echo
echo "-- validate --"
python3 -c "
import json, re, sys
s = re.sub(r'//.*', '', open('$OUT').read())
d = json.loads(s)
a = d['properties']['rdma_dev_addr_list']
print('   rdma_dev_addr_list:', a)
print('   rdma_peer_type:    ', d['properties']['rdma_peer_type'])
sys.exit(0 if a else 1)
"
